INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Nuevo Los Cármenes',194,'16 de mayo de 1995');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('La Romareda',3360,'8 de septiembre de 1957 (64 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Camp Nou',993,'24 de septiembre de 1957 (64 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Abanca-Riazor',3488,'28 de octubre de 1944 (77 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Wanda Metropolitano',0,'4 de septiembre de 1994(Estadio de Madrid)16 de septiembre de 2017(Estadio Metropolitano)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Ciudad de Valencia',2635,'1969');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Virgen de las Nieves',0,'null');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Campo de fútbol Luis Oliver',0,'null');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Municipal El Molinón-Enrique Castro Quini',300,'c. 1908[2]​');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Benito Villamarín',607,'17 de marzo de 1929 (92 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Nuevo Castalia',155,'17 de junio de 1987');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Santiago Bernabéu',810,'14 de diciembre de 1947 (74 años)[3]​');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Balaídos',2900,'30 de diciembre de 1928 (93 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('RCDE Stadium',405,'2 de agosto de 2009 (12 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Estadio Vivar Téllez',300,'18 de julio de 1951');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('San Mamés',533,'16 de septiembre de 2013 (8 años)[5]​');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Pallafría',0,'null');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Son Moix',2050,'3 de julio de 1999');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Campo de Fútbol de Vallecas',1470,'6 de junio de 1976 (45 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Nuevo Lasesarre',796,'30 de septiembre de 2003');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Municipal de Pasarón',1200,'1965');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Narcís Sala',657,'19 de marzo de 1970');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Nou Estadi',1459,'2 de febrero de 1972 (50 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Martínez Valero',3373,'8 de septiembre de 1976 (45 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Municipal Reino de León',1345,'20 de mayo de 2001 (20 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Ramón Sánchez-Pizjuán',438,'7 de septiembre de 1958 (63 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Heliodoro Rodríguez López',229,'25 de julio de 1925 (96 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('José Zorrilla',2761,'20 de febrero de 1982 (40 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('José Rico Pérez',3000,'3 de agosto de 1974 (47 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Enrique Roca de Murcia',3117,'11 de octubre de 2006 (15 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Ramón de Carranza',2072,'3 de septiembre de 1955');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Nova Creu Alta',1198,'20 de agosto de 1967');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Nuevo Arcángel',218,'7 de noviembre de 1993[4]​');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Las Gaunas',1666,'28 de febrero de 2002');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('El Sadar',235,'2 de septiembre de 1967 (54 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('El Sardinero',0,'null');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Pistas del Helmántico',1734,'8 de abril de 1970 (51 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Nuevo Colombino',2167,'8 de noviembre de 2001');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Mendizorroza',1984,'27 de abril de 1924 (97 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Olímpic de Terrassa',115,'1960');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Ciudad de Puertollano',724,'Noviembre de 2010');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('La Victoria',1256,'29 de agosto de 2001');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Cerro del Espino',380,'1995Reformado en 2018');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('A Malata',1204,'29 de agosto de 1993');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Nuevo Mirador',730,'1999');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Municipal Alfonso Murube',650,'1933[1]​');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Cartagonova',1510,'7 de febrero de 1988');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Municipal de Chapín',2052,'28 de junio de 1988 (33 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Las Llanas',436,'9 de septiembre de 1923 (98 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Carlos Belmonte',1800,'9 de septiembre de 1960');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Municipal de Vilatenim',0,'null');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Camp dEsports',0,'null');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Municipal de Ipurúa',81,'14 de septiembre de 1947');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Nou Estadi de Palamós',0,'null');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Suárez Puerta',540,'26 de septiembre de 1943');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Romano',1453,'24 de mayo de 1953 (68 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Multiusos de San Lázaro',120,'24 de junio de 1993');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Nuevo Vivero',1489,'2 de diciembre de 1998 (23 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Anxo Carro',71,'31 de agosto de 1974');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('El Madrigal',0,'null');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Municipal de Butarque',1245,'14 de febrero de 1998 (24 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Francisco de la Hera',1158,'Antiguo: 12 de octubre de 1951 (70 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Juegos Mediterráneos',152,'31 de julio de 2004');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Nuevo Los Pajaritos',82,'14 de enero de 1999 (23 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Gran Canaria',323,'8 de mayo de 2003 (18 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('El Toralín',843,'5 de septiembre de 2000 (21 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Municipal de Montilivi',1128,'14 de agosto de 1970 51 años');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('El Alcoraz',912,'16 de enero de 1972');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Municipal de La Salud',0,'null');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Santo Domingo',51,'1999');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Pedro Escartín',650,'17 de septiembre de 1967');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('El Collao',485,'1921');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Municipal de Anduva',575,'22 de enero de 1950 (72 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('O Couto',565,'29 de agosto de 1948 (73 años)');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Antonio Franco Navarro',2058,'1976');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Estadio Fco. Artés Carrasco',812,'6 de marzo de 2003');
INSERT INTO estadios (nombre, capacidad, fechaInauguracion) VALUES ('Municipal de Sto. Domingo',787,'2001');
